#!/usr/bin/env python3
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

import os
import sys

from burpalyzer_debugging import debug
from chat_parser import simple_to_human_readable, raw_to_simple
from file_tools import read_json, write_lines


# -------------------------------------------------------------------------------------------


def convert_folder_to_human_readable(indir, outdir):
    for folder, subfolders, files in os.walk(indir):
        for file in files:
            filePath = os.path.join(os.path.abspath(folder), file)
            debug("Reading " + filePath)
            data = read_json(filePath)
            simple = raw_to_simple(data)
            human_readable_lines = simple_to_human_readable(simple)
            outfilename = os.path.join(outdir, file.replace("rawlog", "readable"))
            write_lines(outfilename, human_readable_lines)


def main():
    if len(sys.argv) != 3:
        raise ValueError("Invalid number of arguments")
    indir = sys.argv[1]
    outdir = sys.argv[2]

    convert_folder_to_human_readable(indir, outdir)


if __name__ == "__main__":
    main()
